//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoSo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CoSo()
        {
            this.DanhMucSans = new HashSet<DanhMucSan>();
            this.PhanCongs = new HashSet<PhanCong>();
        }
    
        public string MaCS { get; set; }
        public string TenCS { get; set; }
        public string HinhAnh { get; set; }
        public string DiaChi { get; set; }
        public string LinkMap { get; set; }
        public string MucGia { get; set; }
        public string MaLoaiCS { get; set; }
    
        public virtual LoaiCoSo LoaiCoSo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhMucSan> DanhMucSans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanCong> PhanCongs { get; set; }
    }
}
